### ISSUE TITLE
clang-13: error: clang frontend command failed with exit code 139 (use -v to see invocation)

### ISSUE THREAD

**Issue by TogoFire** [kdrag0n/proton-clang#10]
Log: https://del.dog/jyrfevuwyp.txt

this error started to happen after the update: Update to 20210206 build https://github.com/kdrag0n/proton-clang/commit/52046ead315ba79f421dc132e6f91f61a5db7735

----------------------------------------------------------------------------------------------
Update to 20210213 build https://github.com/kdrag0n/proton-clang/commit/fd7cde714b52c45a63f9c47363a528bebb21323f

Log: https://del.dog/lofimapeto.txt

**Comment by Sarisan** [comment]
Same here

**Comment by redstarksten** [comment]
Maybe your source issue. I dont have any problems using latest proton clang commit.

**Comment by ppajda** [comment]
Happend to me too, will try to remove some optimizations and polly from makefile. Maybe that will help.

**Comment by TogoFire** [comment]
> Happend to me too, will try to remove some optimizations and polly from makefile. Maybe that will help.
> Edit: removed polly and all is ok now

Thx bro.

https://github.com/TogoFire/kernel_xiaomi_panda/commit/5662f3fc033aa0d84d098685fb8f7deda1b3fece

**Comment by Sarisan** [comment]
Its intended for compile with polly, so better dont close issue

**Comment by TogoFire** [comment]
ahh. true

**Comment by redstarksten** [comment]
> > Happend to me too, will try to remove some optimizations and polly from makefile. Maybe that will help.
> > Edit: removed polly and all is ok now
> 
> Thx bro.
> 
> [TogoFire/kernel_xiaomi_panda@5662f3f](https://github.com/TogoFire/kernel_xiaomi_panda/commit/5662f3fc033aa0d84d098685fb8f7deda1b3fece)

The kernel has successful compiled (with CONFIG_LLVM_POLLY=y), but kernel size a little bit smaller. Then when I test to flash the kernel, It wont boot.  I did recompile and reflash kernel (using my personal toolchain) just want to make sure that is latest proton clang issue's, the result is, kernel success to boot. So it is confirmed, latest llvm revision using by latest proton clang is the cause of it.

**Comment by kdrag0n** [comment]
This is now handled properly:

> fatal error: error in backend: Option -polly-run-dce not supported with NPM
> PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.

Lack of support for Polly dead code elimination in the new optimization pass manager is an upstream LLVM issue. Please submit an upstream bug report if you want it to be added.

**Comment by Sarisan** [comment]
> This is now handled properly:
> 
> > fatal error: error in backend: Option -polly-run-dce not supported with NPM
> > PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
> 
> Lack of support for Polly dead code elimination in the new optimization pass manager is an upstream LLVM issue. Please submit an upstream bug report if you want it to be added.

Dude, can you test your clang before release? Its stable only one time of 4 releases.

**Comment by kdrag0n** [comment]
This toolchain is bleeding-edge by design and the entire build process is automated. Don't update to every new commit immediately if you need something stable; pick a stable commit and stick to it until you're ready to update.

There are rarely actual compiler issues with anything other than Polly. Breaking changes are not problems with the toolchain, they are intentional changes from upstream LLVM that will make it downstream sooner or later. Using a bleeding-edge toolchain just introduces you to the changes early. This may not be the toolchain for you if you're not willing to deal with that.

**Comment by SupremMotu** [comment]
It should be fixed now with this commit, although I could be wrong
https://github.com/llvm/llvm-project/commit/8796451d6eee1d29b921fc25b62b4b474cdb5eba

**Comment by kdrag0n** [comment]
> It should be fixed now with this commit, although I could be wrong
> [llvm/llvm-project@8796451](https://github.com/llvm/llvm-project/commit/8796451d6eee1d29b921fc25b62b4b474cdb5eba)

Good catch, that should be available in the next build in 3 days.
