### ISSUE TITLE
20210403 breaks building on 4.14

### ISSUE THREAD

**Issue by GtrCraft** [kdrag0n/proton-clang#12]
MODPOST vmlinux.o
security/selinux/avc.o: in function `avc_denied':
/home/gtrcraft/android/kernel/optimus_surya/out/../security/selinux/avc.c:985:(.text+0x17f8): relocation truncated to fit: R_AARCH64_ADR_PREL_PG_HI21 against symbol `selinux_enforcing' defined in .bss.rtic section in security/selinux/hooks.o
security/selinux/hooks.o: in function `selinux_set_mnt_opts':
/home/gtrcraft/android/kernel/optimus_surya/out/../security/selinux/hooks.c:729:(.text+0x448): relocation truncated to fit: R_AARCH64_ADR_PREL_PG_HI21 against symbol `ss_initialized' defined in .bss.rtic section in security/selinux/ss/services.o
security/selinux/hooks.o: in function `__inode_security_revalidate':
/home/gtrcraft/android/kernel/optimus_surya/out/../security/selinux/hooks.c:267:(.text+0x17d8): relocation truncated to fit: R_AARCH64_ADR_PREL_PG_HI21 against symbol `ss_initialized' defined in .bss.rtic section in security/selinux/ss/services.o
/home/gtrcraft/android/kernel/optimus_surya/out/../security/selinux/hooks.c:267:(.text+0x1ac0): relocation truncated to fit: R_AARCH64_ADR_PREL_PG_HI21 against symbol `ss_initialized' defined in .bss.rtic section in security/selinux/ss/services.o
security/selinux/hooks.o: in function `selinux_nlmsg_perm':
/home/gtrcraft/android/kernel/optimus_surya/out/../security/selinux/hooks.c:5155:(.text+0x1cb0): relocation truncated to fit: R_AARCH64_ADR_PREL_PG_HI21 against symbol `selinux_enforcing' defined in .bss.rtic section in security/selinux/hooks.o
security/selinux/hooks.o: in function `__inode_security_revalidate':
/home/gtrcraft/android/kernel/optimus_surya/out/../security/selinux/hooks.c:267:(.text+0x1e30): relocation truncated to fit: R_AARCH64_ADR_PREL_PG_HI21 against symbol `ss_initialized' defined in .bss.rtic section in security/selinux/ss/services.o
/home/gtrcraft/android/kernel/optimus_surya/out/../security/selinux/hooks.c:267:(.text+0x2b70): relocation truncated to fit: R_AARCH64_ADR_PREL_PG_HI21 against symbol `ss_initialized' defined in .bss.rtic section in security/selinux/ss/services.o
security/selinux/hooks.o: in function `selinux_get_mnt_opts':
/home/gtrcraft/android/kernel/optimus_surya/out/../security/selinux/hooks.c:608:(.text+0x2e7c): relocation truncated to fit: R_AARCH64_ADR_PREL_PG_HI21 against symbol `ss_initialized' defined in .bss.rtic section in security/selinux/ss/services.o
security/selinux/hooks.o: in function `__inode_security_revalidate':
/home/gtrcraft/android/kernel/optimus_surya/out/../security/selinux/hooks.c:267:(.text+0x32e8): relocation truncated to fit: R_AARCH64_ADR_PREL_PG_HI21 against symbol `ss_initialized' defined in .bss.rtic section in security/selinux/ss/services.o
security/selinux/hooks.o: in function `selinux_sb_clone_mnt_opts':
/home/gtrcraft/android/kernel/optimus_surya/out/../security/selinux/hooks.c:1012:(.text+0x3404): relocation truncated to fit: R_AARCH64_ADR_PREL_PG_HI21 against symbol `ss_initialized' defined in .bss.rtic section in security/selinux/ss/services.o
security/selinux/hooks.o: in function `__inode_security_revalidate':
/home/gtrcraft/android/kernel/optimus_surya/out/../security/selinux/hooks.c:267:(.text+0x37fc): additional relocation overflows omitted from the output
make[1]: *** [/home/gtrcraft/android/kernel/optimus_surya/Makefile:1117: vmlinux] Error 1

**Comment by kdrag0n** [comment]
https://android.googlesource.com/kernel/msm/+/d9d36ace40ca279bf6841a0843b72600b10ae17e
