### ISSUE TITLE
20210403 Hardcoded(?) lib path on aarch64-linux-gnu-ld.gold

### ISSUE THREAD

**Issue by TenSeventy7** [kdrag0n/proton-clang#13]
Building kernel fails when `aarch64-linux-gnu-ld.gold` exports lib-ksyms with a "Permission denied" error, with it trying to access `/root/build/install/aarch64-linux-gnu/lib`. I've checked my kernel sources and it doesn't have these harcoded.

```
  CC      sound/soc/soc-pcm.o
  AS      arch/arm64/lib/strlen.o
  AS      arch/arm64/lib/strncmp.o
  AS      arch/arm64/lib/strnlen.o
  AS      arch/arm64/lib/strrchr.o
  CC      sound/soc/soc-io.o
  AR      arch/arm64/lib/lib.a
  EXPORTS arch/arm64/lib/lib-ksyms.o
/home/tenseventy7/proton-clang/bin/aarch64-linux-gnu-ld.gold: error: /root/build/install/aarch64-linux-gnu/lib: can not read directory: Permission denied
make[1]: *** [scripts/Makefile.build:609: arch/arm64/lib/lib-ksyms.o] Error 1
make: *** [Makefile:1232: arch/arm64/lib] Error 2
make: *** Waiting for unfinished jobs....
```

While this generally won't be a problem when building on CI (since they usually run on root), local builds fail unless I do somewhat dangerous `chown`s to the /root folder.

**Comment by pix106** [comment]
@TenSeventy7 were you able to solve this ?

**Comment by goshawk22** [comment]
I also have this issue - did you find a fix?

**Comment by radu-v** [comment]
was just going to open an issue for this 😆 
git bisect says this was introduced with version `20210403`, commit 5cade6cb315fc7f29be3b8abb4a1c60680ead5af.
Last version that doesn't have this problem is `20210327`, commit 023c0eec1ed50a5ebcc91ba3a8230e7227b8f7ba.

**Comment by TenSeventy7** [comment]
The issue seems have been resolved with the `20210522` build. Closing.

**Comment by pix106** [comment]
> The issue seems have been resolved with the `20210522` build. Closing.

Are you sure ?
After removing my local workaround (empty /root/build/install/aarch64-linux-gnu/lib dir), problem is still there.

**Comment by Dark-Matter7232** [comment]
Can confirm it error still exists on 20210522.

**Comment by eun0115** [comment]
hey there! its almost a year and the error still exist
