### ISSUE TITLE
Clamg 14

### ISSUE THREAD

**Issue by ghost** [kdrag0n/proton-clang#15]
When clang 14 will come

**Comment by kdrag0n** [comment]
Proton Clang hasn't been updated since May because libclang-cpp.so.13git grew bigger than 100 MiB with LTO + PGO, which exceeds GitHub's file size limit. It could be migrated to GitLab, but I'm not sure I have time to maintain this project anymore.

**Comment by ghost** [comment]
> Proton Clang hasn't been updated since May because libclang-cpp.so.13git grew bigger than 100 MiB with LTO + PGO, which exceeds GitHub's file size limit. It could be migrated to GitLab, but I'm not sure I have time to maintain this project anymore.

@kdrag0n There's a nice and quick workaround for that, using only two simple bash commands...

```
#!/bin/bash
# To split
split -b99M libclang-cpp.so.13git libclang-cpp.so.13git.
# To join
cat libclang-cpp.so.13git.?? > libclang-cpp.so.13git
```
Chances of file corruption is very unlikely.
