### ISSUE TITLE
20200725 build errors with aarch64

### ISSUE THREAD

**Issue by v4lkyr** [kdrag0n/proton-clang#2]
Hello Danny,

Latest build (20200725) has below errors with aarch64 kernel build:

../toolchains/proton-clang/bin/ld: unrecognised emulation mode: aarch64linux
Supported emulations: elf_x86_64 elf32_x86_64 elf_i386 elf_iamcu elf_l1om elf_k1om i386pep i386pe
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)

However, when I hard reset the head back to 20200719 build, everything works all good.

My regards.

**Comment by kdrag0n** [comment]
This is caused by a [breaking change](https://github.com/llvm/llvm-project/commit/3452a0d8c17f7166f479706b293caf6ac76ffd90) in upstream Clang. I just posted the fix in the Telegram channel:

> Clang's cross-compiling behavior has changed, causing errors like `unrecognized option '-EL'` when building Linux kernels. Here is the fix from upstream which you can either cherry-pick now or wait for linux-stable to merge: https://github.com/kdrag0n/proton_zf6/commit/6e87fec9a3df5

**Comment by kdrag0n** [comment]
Here's the fix for another error you might encounter:

> If you are still experiencing the error in vdso32 after picking the commit above, pick ["arm64: vdso32: Fix '--prefix=' value for newer versions of clang"](https://kdrag0n.dev/gcp/zf6/68acd6966ac98) to fix it. This patch will not be backported to linux-stable trees older than 5.4 because vdso32 didn't exist in mainline back then, so you will most likely need to pick it manually.

**Comment by v4lkyr** [comment]
Thank you Danny.
