### ISSUE TITLE
20200825 build errors with aarch64

### ISSUE THREAD

**Issue by v4lkyr** [kdrag0n/proton-clang#3]
Hello Danny,

Latest build (20200825) has below errors with aarch64 kernel build:

  GEN     .version
  CHK     include/generated/compile.h
  UPD     include/generated/compile.h
  CC      init/version.o
  AR      init/built-in.o
  AR      built-in.o
  LTO     vmlinux.o
  MODPOST vmlinux.o
/home/v4lkyr/android/tools/toolchains/proton-clang/bin/aarch64-linux-gnu-ld: vmlinux.o: in function `alloc_tty_struct':
(.text+0x591b24): undefined reference to `stpcpy'
/home/v4lkyr/android/tools/toolchains/proton-clang/bin/aarch64-linux-gnu-ld: vmlinux.o: in function `tty_register_device_attr':
(.text+0x593c88): undefined reference to `stpcpy'
/home/v4lkyr/android/tools/toolchains/proton-clang/bin/aarch64-linux-gnu-ld: vmlinux.o: in function `show_cons_active':
tty_io.c:(.text+0x595b20): undefined reference to `stpcpy'
/home/v4lkyr/android/tools/toolchains/proton-clang/bin/aarch64-linux-gnu-ld: vmlinux.o: in function `ctp_selftest_proc_read':
lct_ctp_selftest.c:(.text+0x806e44): undefined reference to `stpcpy'
/home/v4lkyr/android/tools/toolchains/proton-clang/bin/aarch64-linux-gnu-ld: vmlinux.o: in function `ctp_upgrade_proc_read':
lct_ctp_upgrade.c:(.text+0x80713c): undefined reference to `stpcpy'
/home/v4lkyr/android/tools/toolchains/proton-clang/bin/aarch64-linux-gnu-ld: vmlinux.o:lct_if_ctp_upgrade.c:(.text+0x807504): more undefined references to `stpcpy' follow
make[1]: *** [/home/v4lkyr/android/xiaomi/whyred/Makefile:1134: vmlinux] Error 1
make[1]: Leaving directory '/home/v4lkyr/android/xiaomi/whyred/out'
make: *** [Makefile:152: sub-make] Error 2

However, when I hard reset the head back to 20200808 build, everything works all good.

My regards.

**Comment by attack11** [comment]
https://github.com/kdrag0n/proton_zf6/commit/cec73f0775526

**Comment by v4lkyr** [comment]
Thank you, @attack11 that fixed my problem.

However, I think Danny should update the readme for this particular error, as there might be others like me who'll come up to this problem.

I guess I need to follow proton_clang channel on TG for updates.

**Comment by kdrag0n** [comment]
Fix added to readme.
