### ISSUE TITLE
20200831 build warnings

### ISSUE THREAD

**Issue by Jabiyeff** [kdrag0n/proton-clang#4]
Hi sir

Latest build (20200831) has below warnings with aarch64 kernel build

In file included from ../techpack/audio/asoc/msm8952-dai-links.c:14:
In file included from ../include/sound/core.h:25:
In file included from ../include/linux/device.h:24:
In file included from ../include/linux/pinctrl/devinfo.h:21:
In file included from ../include/linux/pinctrl/consumer.h:17:
In file included from ../include/linux/seq_file.h:10:
In file included from ../include/linux/fs.h:7:
../include/linux/dcache.h:502:9: warning: '}' and ')' tokens terminating statement expression are separated by whitespace [-Wcompound-token-split-by-space]
        return mult_frac(val, sysctl_vfs_cache_pressure, 100);
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/linux/kernel.h:134:50: note: expanded from macro 'mult_frac'
        (quot * (numer)) + ((rem * (numer)) / (denom)); \
                                                        ^
2 warnings generated.
  CC      net/core/gen_stats.o
In file included from ../net/core/scm.c:23:
In file included from ../include/linux/net.h:28:
In file included from ../include/linux/fs.h:7:

Old build working good. no any warnings (20200825)

My regards.

**Comment by kdrag0n** [comment]
I would recommend ignoring these warnings until a fix is in upstream, as tracked by https://github.com/ClangBuiltLinux/linux/issues/1145. 

If you really want this fixed immediately, you can try applying the patch here as a temporary workaround and reverting it in favor of newer patches once it's fixed in upstream: https://github.com/ClangBuiltLinux/linux/issues/1145#issue-688505721

**Comment by Jabiyeff** [comment]
> I would recommend ignoring these warnings until a fix is in upstream, as tracked by [ClangBuiltLinux/linux#1145](https://github.com/ClangBuiltLinux/linux/issues/1145).
> 
> If you really want this fixed immediately, you can try applying the patch here as a temporary workaround and reverting it in favor of newer patches once it's fixed in upstream: [ClangBuiltLinux/linux#1145 (comment)](https://github.com/ClangBuiltLinux/linux/issues/1145#issue-688505721)

Yes thanks sir fixed now, i am waiting new update to revert it.

**Comment by Jabiyeff** [comment]
Commit link: https://github.com/Jabiyeff/msm-4.9-santoni-10/commit/330795b9dd90d944711564d585561811b63ae67d
