### ISSUE TITLE
Building kernel tooks forever

### ISSUE THREAD

**Issue by semdoc** [kdrag0n/proton-clang#9]
After "Update to 20210116 build" commit, building kernel tooks forever. 

Any known issues??

Thanx,

**Comment by Sarisan** [comment]
I faced this too

**Comment by semdoc** [comment]
resetted locallay to the previous commit (this: https://github.com/semdoc/proton-clang/commit/4c4415a724ac9dfc7eb0a13fd6e9d39eb59dd42a ) and all is fine again.

**Comment by semdoc** [comment]
fixed in kernel.
